- hosts: localhost
  connection: local
  become: yes
  roles:
    - init
    - install-from-package-manager
    - install-manually
    - services
    - zsh
    - sdkman
    - vim
    - dotfiles
    - desktop
    - os
