- hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Check if zplug is installed
    shell: test -e /home/tanabe/.zplug/zplug && echo "yes" || echo "no"
    register: is_zplug_installed

  - name: Install zplug
    when: is_zplug_installed.stdout == "no"
    shell: curl -fLo ~/.zplug/zplug --create-dirs git.io/zplug
    become: no

  - name: Copy .zshrc
    copy: src=./.zshrc dest=/home/tanabe/.zshrc
    become: no

  - name: Copy zsh settings
    copy: src=./.zsh dest=/home/tanabe
    become: no
