- name: No caps
  command: gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
  become: no

- name: Show log out
  command: gsettings set org.gnome.shell always-show-log-out true
  become: no

- name: Show date
  command: gsettings set org.gnome.desktop.interface clock-show-date true
  become: no
