- name: Copy limits.conf
  copy: src=./os/nproc_nofile.conf dest=/etc/security/limits.d/nproc_nofile.conf

- name: Make my tuned settings dir
  file: path=/etc/tuned/my-desktop state=directory

- name: Copy my tuned.conf
  copy: src=./os/tuned.conf dest=/etc/tuned/my-desktop/tuned.conf

- name: Enable my tuned settings
  command: tuned-adm profile my-desktop

- name: Run system activity accounting tool every 1 minutes
  cron: name="Run sar every 1 min" job="/usr/lib64/sa/sa1 1 1" user="root"

- name: Generate a daily summary of process accounting
  cron: name="Daily performance summary" job="/usr/lib64/sa/sa2 -A" minute=53 hour=23 user="root"
